title: Albireo
description: No man ever steps in the same river twice.
author: Zhiyuan Zheng
avatar: /weblogo.png
email: zyzhengnju@gmail.com
skin: daylight
location: Nanjing, CN
subscribe: False
lang: en
introduction: PhD student in astrophysics at School of Astronomy & Space Science | Nanjing University.

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec
  - vendor

# Jekyll SEO Tag (Optional)
# =========================
# logo: weblogo.png
social:
  name: Zhiyuan Zheng
  links:
    - https://github.com/shiro1920
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx

